global:
  task: "attribute_prediction"
  gpu_id: 0
  seed: 42
  num_classes: 20
  num_attributes: 64
  num_epochs: 100
  metrics_step:
    - progress: 0.4
      step: 10
    - progress: 0.8
      step: 5
    - progress: 0.9
      step: 2
    - progress: 1.
      step: 1

transform:
  resize_values: 600 # shortest edge
  max_size: 1000
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

preprocessing:
  n_images: 2
  n_roi_per_image: 64
  ratio_pos_roi: 0.25
  iou_thresh_low_neg: 0.1
  iou_thresh_low_pos: 0.5

postprocessing:
  max_roi_per_image: 100
  nms_iou_threshold: 0.3
  score_threshold: 0.05

model:
  #load_pretrained_model: "models/object_detection/model_2024-06-15_11-59.pth"
  spatial_scale: 0.0625
  output_size_roipool: [7, 7] # [6,6]

loss:
  lmb_cls: 1.
  lmb_loc: 1.

optimizer:
  lr_global: 0.001
  momentum: 0.9
  weight_decay: 0.0005
  lr_weigth_mult: 1
  lr_bias_mult: 2
  sched_step_size: 40
  sched_gamma: 0.1
