global:
  num_classes : 20
  num_attributes: 64

device:
  gpu_id: 0

reproducibility:
  seed: 42

preprocessing:
  n_images: 2
  n_roi_per_image: 64
  ratio_pos_roi: 0.25
  bbox_normalize_means: [0.0, 0.0, 0.0, 0.0]
  bbox_normalize_stds: [0.1, 0.1, 0.2, 0.2]
  iou_thresh_low_neg: 0.1
  iou_thresh_low_pos: 0.5

postprocessing:
  max_roi_per_image: 100 
  iou_threshold: 0.1

transform:
    resize_values: [600, 600] # (H, W)
    mean: [0.485, 0.456, 0.406]  
    std: [0.229, 0.224, 0.225]  

val_set:
 val_size: 0.1 # not used

training_loop:
  num_epochs: 60 

model:
  spatial_scale: 0.06
  out_size_roi_pool: [6,6]

loss:
 lmb_cls: 1
 lmb_loc: 1

optimizer:
  lr_global: 0.001
  momentum: 0.9
  weight_decay: 0.0005
  lr_weigth_mult: 1
  lr_bias_bias: 2
  sched_step_size: 30
  sched_gamma: 0.1
  